### ISSUE TITLE
Unable to find version `v1`

### ISSUE THREAD

**Issue by MarcelReiter** [fossology/fossology-action#4]
I tried using this github action and failed:

```
Error: Unable to resolve action fossology/fossology-action@v1, unable to find version v1
```

Looking [at the releases page](https://github.com/fossology/fossology-action/releases) it seems pretty clear why:
There doesn't seem to be a release of this action.

This leaves me with a few of questions
- Am i doing something wrong?
- Could you add a bold disclaimer "Not released yet" to the readme?
- Is there any estimate on when there will be a release?
- Could you please confirm that [this setup using docker](https://github.com/fossology/fossology/blob/master/utils/automation/.github-workflow.yml) is the best alternative for the time being?

---
My current code basically equals your readme
```
on:
  pull_request:

jobs:
  check-license:
    name: Check license
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Run Scanners
        id: compliance
        uses: fossology/fossology-action@v1
        with:
          scanners: 'nomos ojo copyright keyword'
```
